USE [BKI_IMP_EXP]

GO

DECLARE @CONTRACT VARCHAR(20)
DECLARE @DELIVERY VARCHAR(20)

SET @CONTRACT = '13-376'
SET @DELIVERY = '1'

SELECT DISTINCT
	LR.[S_CONTRACT_NO] AS [CONTRACT NO]
	,LR.[S_DELIVERY_NAME] AS [DELIVERY]
	,LR.[S_TYPE_CELL] AS [CUSTOMER CODE]
	,LR.[PRODUCTION_ORDER_ID] AS [ROASTING ORDER ID]
	,LG.[PRODUCTION_ORDER_ID] AS [GRINDING ORDER ID]
	,PB.[PRODUCTION_ORDER_ID] AS [PB ORDER ID]
	,PG.[PRODUCTION_ORDER_ID] AS [PG ORDER ID]
FROM [dbo].[PRO_EXP_ORDER_LOAD_R] AS LR
LEFT JOIN [dbo].[PRO_EXP_ORDER_UNLOAD_R] AS ULR
	ON LR.[PRODUCT_ID] = ULR.[S_PRODUCT_ID]
LEFT JOIN [dbo].[PRO_EXP_ORDER_SEND_PB] AS PB
	ON ULR.[S_PRODUCT_ID] = PB.[S_PRODUCT_ID]
LEFT JOIN [dbo].[PRO_EXP_ORDER_LOAD_G] AS LG
	ON ULR.[S_PRODUCT_ID] = LG.[S_PRODUCT_ID]
LEFT JOIN [dbo].[PRO_EXP_ORDER_UNLOAD_G] AS ULG
	ON LG.[PRODUCT_ID] = ULG.[S_PRODUCT_ID]
LEFT JOIN [dbo].[PRO_EXP_ORDER_SEND_PG] AS PG
	ON ULG.[S_PRODUCT_ID] = PG.[S_PRODUCT_ID]
WHERE LR.[S_CONTRACT_NO] = @CONTRACT
	AND LR.[S_DELIVERY_NAME] = @DELIVERY